support for run_test_cb & shellcheck fix
sclorg/container-common-scripts pull request #268
Opened 2022-06-16 12:42 UTC by zmiklank

This change should be backward compatible. It is needed because of moving s2i-nodejs container tests to generic test function. However, I suppose there will be also other containers like this.
See some info in the commit message.

The second commit adds an ignore for shellcheck.

2022-06-16 12:43 UTC, zmiklank commented
[test-all]

2022-06-16 13:05 UTC, zmiklank commented
I have rebased on master.
[test-all]

2022-06-27 10:10 UTC, phracek commented
Sorry, I don't follow what means this change. In case `run_test_cb` is not function, then we call function run_test_cb?

Any examples for my understanding would be nice. In this case, I am a newbie;)

2022-06-27 10:10 UTC, phracek requested changes
Sorry, I don't follow what means this change. In case run_test_cb is not function, then we call function run_test_cb?

Any examples for my understanding would be nice. In this case, I am a newbie;)

2022-06-27 10:22 UTC, zmiklank commented
Sure.

Some containers (in this case the s2i-nodejs one) have more complex test execution than ordinary container images. These can write their own function for this, as in [here](https://github.com/sclorg/s2i-nodejs-container/blob/949fb4526e4254c87dcc9391ff30133940a0b52b/test/run#L131).
If this is not needed, then the `run_test_cb` is defined directly in the `ct_run_tests_from_testset`, see here https://github.com/sclorg/container-common-scripts/blob/09e45fc6ab0c29f8cb2b61b0f8278a2f472aaa43/test-lib.sh#L1147
The `run_test_cb` is defined in `ct_run_tests_from_testset`, only if not defined before.

2022-06-30 08:02 UTC, phracek commented
@zmiklank This is not needed now, I guess. Right?

2022-06-30 08:15 UTC, zmiklank commented
Yes, I need to rework this.

2022-06-30 18:16 UTC, hhorak commented on test-lib.sh
> +      $1
wouldn't `eval $1` be better, so we do not run a sub-shell unnecessarily?

2022-07-12 10:26 UTC, closed without merging