Make cgroup-limits script work for non-root containers
sclorg/container-common-scripts pull request #317
Opened 2022-12-21 14:35 UTC by hhorak

Resource limits detection was enhanced via:
https://github.com/sclorg/container-common-scripts/pull/237 While this is not directly connected, mentioning to connect both issues that touch resource limits detection.

Per podman-run(1) man page, on some systems, changing the resource limits may not be allowed for non-root users. For more details, see https://github.com/containers/podman/blob/main/troubleshooting.md#26-running-containers-with-resource-limits-fails-with-a-permissions-error.

This caused the cgroup-limits script to fail with python traceback:

```
$ podman run -ti --rm quay.io/fedora/s2i-core:37 /usr/bin/cgroup-limits Warning: Can't detect cpu quota from cgroups
Warning: Can't detect cpuset size from cgroups
Traceback (most recent call last):
  File /usr/bin/cgroup-limits, line 143, in <module>
    NUMBER_OF_CORES: get_number_of_cores()
                       ^^^^^^^^^^^^^^^^^^^^^
  File /usr/bin/cgroup-limits, line 76, in get_number_of_cores
    return min([l for l in limits if l])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: min() arg is an empty sequence
```

This change implements another way to see number of CPUs (without cgroups), using nproc tool.

This might work as the last resort when running a container as non-root, so we get the same output as when the same container is run as a root on the same machine.

Also tracked internally: https://issues.redhat.com/browse/RHELPLAN-141599

2022-12-22 07:35 UTC, hhorak commented
[test]

2023-01-02 09:31 UTC, phracek commented
[test-all]

2023-01-02 12:27 UTC, phracek requested changes
The pull request itself LGTM, but I have hit some issues on RHEL7 machine:

Python 2.7 traceback:
```bash
$ ./shared-scripts/core/usr/bin/cgroup-limits
Traceback (most recent call last):
  File "./shared-scripts/core/usr/bin/cgroup-limits", line 180, in <module>
    "NUMBER_OF_CORES": get_number_of_cores()
  File "./shared-scripts/core/usr/bin/cgroup-limits", line 97, in get_number_of_cores
    limits = [l for l in [_read_cpu_quota(), _read_cpuset_size(), _read_nproc()] if l]
  File "./shared-scripts/core/usr/bin/cgroup-limits", line 172, in _read_nproc
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

on RHEL7 by calling python-3.6:
```bash
$ python3.6 ./shared-scripts/core/usr/bin/cgroup-limits
Traceback (most recent call last):
  File "./shared-scripts/core/usr/bin/cgroup-limits", line 180, in <module>
    "NUMBER_OF_CORES": get_number_of_cores()
  File "./shared-scripts/core/usr/bin/cgroup-limits", line 97, in get_number_of_cores
    limits = [l for l in [_read_cpu_quota(), _read_cpuset_size(), _read_nproc()] if l]
  File "./shared-scripts/core/usr/bin/cgroup-limits", line 171, in _read_nproc
    return int(subprocess.run('nproc', capture_output=True).stdout)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

2023-01-02 12:29 UTC, phracek reviewed
Python-3.6 does not have a parameter called `capture_output`: https://docs.python.org/3.6/library/subprocess.html

2023-01-02 16:01 UTC, hhorak commented
Thanks, I've re-implemented the `nproc` call to something that should work on both, Python 2 and 3.

2023-01-02 16:01 UTC, hhorak commented
[test-all]

2023-01-03 16:01 UTC, hhorak commented
[test-all]

2023-01-06 11:57 UTC, phracek commented
[test]

2023-01-06 12:18 UTC, hhorak commented
I don't understand why, but some commits from this PR are already merged in master. The remaining fix that fixes #319 is is now separately in #322, so let's close this PR that is not needed in its most part.

2023-01-06 12:18 UTC, closed without merging